
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 27 00:12:23 CST 2019
//----------------------------------------------------

package Compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONDICION_SINO = 12;
  public static final int VARIABLE = 22;
  public static final int MAYOR_QUE = 20;
  public static final int TIPO_DATO_NUMERO = 13;
  public static final int TERMINAR = 9;
  public static final int LITERAL = 10;
  public static final int MEDICAMENTOL = 4;
  public static final int DOS_PUNTOS = 7;
  public static final int INICIAR = 8;
  public static final int COMA = 21;
  public static final int TIPO_DATO_TEXTO = 14;
  public static final int MEDICAMENTOF = 3;
  public static final int GUARDAR = 19;
  public static final int MOSTRAR = 18;
  public static final int EOF = 0;
  public static final int DIGITO = 23;
  public static final int error = 1;
  public static final int LLAVE_C = 17;
  public static final int MEDIDAL = 6;
  public static final int CONDICION_SI = 11;
  public static final int LLAVE_A = 16;
  public static final int PUNTO_COMA = 15;
  public static final int MEDIDAF = 5;
  public static final int FUNCION = 2;
}

